"""add user_bookmarks table

Revision ID: bbdc55996be6
Revises: 48af2ee8d3da
Create Date: 2026-01-05 23:10:31.985572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'bbdc55996be6'
down_revision: Union[str, Sequence[str], None] = '48af2ee8d3da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bookmarks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('chapter_id', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bookmarks_chapter_id'), 'user_bookmarks', ['chapter_id'], unique=False)
    op.create_index(op.f('ix_user_bookmarks_user_id'), 'user_bookmarks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bookmarks_user_id'), table_name='user_bookmarks')
    op.drop_index(op.f('ix_user_bookmarks_chapter_id'), table_name='user_bookmarks')
    op.drop_table('user_bookmarks')
    # ### end Alembic commands ###
